name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

env:
  BUILD_CONFIGURATION: Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Test Image
        run: docker compose build

      - name: Check Format
        run: docker compose run --rm playwright-tests sh -c "./build.sh CheckFormat"

      - name: Run Tests
        run: docker compose run --rm playwright-tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x"

      - uses: actions/setup-node@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Restore Tools
        run: dotnet tool restore

      - name: Build Pipeline
        run: ./build.sh BuildDocs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: src/Weave.Docs/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
